Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2020-11, with the labels that each got.

#52 New concept and API for product importers
  src/Moryx.AbstractionLayer/Products/IProductManagement.cs
  src/Moryx.AbstractionLayer/Products/Import/FileImportParameters.cs
  src/Moryx.AbstractionLayer/Products/Import/IFileImportParameters.cs
  src/Moryx.AbstractionLayer/Products/Import/IImportParameters.cs
  src/Moryx.AbstractionLayer/Products/Import/IPrototypeParameters.cs
  src/Moryx.AbstractionLayer/Products/Import/PrototypeImportParameters.cs
  src/Moryx.AbstractionLayer/Products/ProductImportResult.cs
  src/Moryx.Products.Management/Components/IProductImporter.cs
  src/Moryx.Products.Management/Components/IProductManager.cs
  src/Moryx.Products.Management/Components/ProductImportContext.cs
  src/Moryx.Products.Management/Components/ProductImporterResult.cs
  src/Moryx.Products.Management/Facades/ProductManagementFacade.cs
  src/Moryx.Products.Management/Implementation/Import/ProductImporterBase.cs
  src/Moryx.Products.Management/Implementation/ImportState.cs
  src/Moryx.Products.Management/Implementation/ProductManager.cs
  src/Moryx.Products.Management/Modification/Model/ImportStateModel.cs
  src/Moryx.Products.Management/Modification/Wcf/IProductInteraction.cs
  src/Moryx.Products.Management/Modification/Wcf/ProductInteraction.cs
  src/Moryx.Products.Management/ModuleController/ModuleConfig.cs
  src/Moryx.Products.Management/Plugins/Importers/DefaultImporter.cs
  src/Moryx.Products.Samples/Importer/FileImporter.cs
  src/Moryx.Products.Samples/Importer/WatchImporter.cs
  src/Moryx.Products.UI.Interaction/Products/Import/ImportViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Import/ImporterViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/ProductsWorkspaceViewModel.cs
  src/Moryx.Products.UI/Connected Services/ProductService/Reference.cs
  src/Moryx.Products.UI/IProductServiceModel.cs
  src/Moryx.Products.UI/ProductServiceModel.cs
Labels: area:ProductManagement, bug, enhancement

#53 Several fixed before beta release
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Resources.Interaction/Converter/ModelToResourceConverter.cs
  src/Moryx.Resources.Interaction/Converter/ResourceToModelConverter.cs
Labels: bug

#54 Support product query with interfaces and base types
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Moryx.Products.Samples/Importer/WatchImporter.cs
  src/Moryx.Products.Samples/ProductInstances/WatchfaceInstance.cs
  src/Moryx.Products.Samples/ProductTypes/WatchType.cs
  src/Moryx.Products.Samples/ProductTypes/WatchfaceType.cs
  src/Tests/Moryx.AbstractionLayer.Tests/ProductTests.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: area:ProductManagement, enhancement

#55 Fix resource reference saving
  src/Moryx.Resources.Interaction/Converter/ModelToResourceConverter.cs
  src/Moryx.Resources.Interaction/Converter/ResourceToModelConverter.cs
  src/Moryx.Resources.Samples/IVisualInstructor.cs
Labels: bug

#56 Forward context to protected product import
  src/Moryx.Products.Management/Components/ProductImportContext.cs
  src/Moryx.Products.Management/Implementation/Import/ProductImporterBase.cs
  src/Moryx.Products.Management/Plugins/Importers/DefaultImporter.cs
  src/Moryx.Products.Samples/Importer/FileImporter.cs
  src/Moryx.Products.Samples/Importer/WatchImporter.cs
Labels: area:ProductManagement, bug

#58 Applied changes after WpfToolkit renaming
  Directory.Build.targets
  src/Moryx.AbstractionLayer.UI/Aspects/AspectConfiguratorViewModel.cs
  src/Moryx.AbstractionLayer.UI/Controls/EditModeButtonControl.xaml.cs
  src/Moryx.AbstractionLayer.UI/MasterDetails/MasterDetailsWorkspace.cs
  src/Moryx.AbstractionLayer.UI/ToolbarButtonStyle.xaml
  src/Moryx.Products.UI.Interaction/ModuleController/ModuleController.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/CollectionPartConnectorViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/SelectPartLinkDialogViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/SinglePartConnectorPartView.xaml
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/SinglePartConnectorPartViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Recipes/AddRecipeDialogView.xaml
  src/Moryx.Products.UI.Interaction/Products/Aspects/Recipes/AddRecipeDialogViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Recipes/RecipesAspectViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Duplicate/DuplicateProductDialogViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Import/ImportViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/ProductsWorkspaceView.xaml
  src/Moryx.Products.UI.Interaction/Products/ProductsWorkspaceViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Removal/RemoveProductViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Revisions/CreateRevisionViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Revisions/RevisionsViewModel.cs
  src/Moryx.Products.UI.Interaction/Recipes/Details/Default/DefaultRecipeDetailsView.xaml
  src/Moryx.Products.UI.Interaction/Recipes/RecipesWorkspaceView.xaml
  src/Moryx.Resources.UI.Interaction/Details/Aspects/References/ReferencesAspectView.xaml
  src/Moryx.Resources.UI.Interaction/Details/Aspects/References/ReferencesAspectViewModel.cs
  src/Moryx.Resources.UI.Interaction/Details/Aspects/References/SelectTargetDialogViewModel.cs
  src/Moryx.Resources.UI.Interaction/Details/Removal/RemoveResourceViewModel.cs
  src/Moryx.Resources.UI.Interaction/ModuleController/ModuleController.cs
  src/Moryx.Resources.UI.Interaction/TypeSelector/TypeSelectorViewModel.cs
  src/Moryx.Resources.UI.Interaction/Workspace/InteractionWorkspaceView.xaml
  src/Moryx.Resources.UI.Interaction/Workspace/InteractionWorkspaceView.xaml.cs
  src/Tests/Moryx.AbstractionLayer.UI.Tests/packages.config
Labels: area:ProductManagement, area:ResourceManagement, enhancement

#59 Update capabilities article
  docs/articles/Processing/Capabilities.md
  docs/articles/Processing/images/capabilities.svg
Labels: area:Abstraction, documentation

#60 Dispose Host in Stop to make sure it was started before
  src/Moryx.Resources.Wcf/InteractionResource.cs
Labels: bug

#62 Fix support of interfaces for parameters in TaskStep
  src/Moryx.AbstractionLayer/Tasks/TaskStep.cs
Labels: area:Abstraction, bug
