Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2020-10, with the labels that each got.

#39 Add ResourceRemoved event on Facade
  src/Moryx.AbstractionLayer/Resources/IResourceManagement.cs
  src/Moryx.Resources.Management/Facades/ResourceManagementFacade.cs
  src/Moryx.Resources.Management/Resources/IResourceManager.cs
  src/Moryx.Resources.Management/Resources/ResourceManager.cs
Labels: area:ResourceManagement, enhancement

#43 Updated platform packages and removed bundle attribute
  src/Moryx.AbstractionLayer.TestTools/Moryx.AbstractionLayer.TestTools.csproj
  src/Moryx.AbstractionLayer.UI/Moryx.AbstractionLayer.UI.csproj
  src/Moryx.AbstractionLayer/AbstractionLayerBundle.cs
  src/Moryx.AbstractionLayer/Moryx.AbstractionLayer.csproj
  src/Moryx.Notifications/Moryx.Notifications.csproj
  src/Moryx.Products.Management/Moryx.Products.Management.csproj
  src/Moryx.Products.Management/Plugins/GenericStrategies/IPropertyMapper.cs
  src/Moryx.Products.Management/Properties/AssemblyInfo.cs
  src/Moryx.Products.Model/Moryx.Products.Model.csproj
  src/Moryx.Products.Samples/Moryx.Products.Samples.csproj
  src/Moryx.Products.UI.Interaction/Moryx.Products.UI.Interaction.csproj
  src/Moryx.Products.UI/Moryx.Products.UI.csproj
  src/Moryx.Resources.Interaction/Moryx.Resources.Interaction.csproj
  src/Moryx.Resources.Interaction/Properties/AssemblyInfo.cs
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
  src/Moryx.Resources.Management/Properties/AssemblyInfo.cs
  src/Moryx.Resources.Samples/Moryx.Resources.Samples.csproj
  src/Moryx.Resources.UI.Interaction/Moryx.Resources.UI.Interaction.csproj
  src/Moryx.Resources.UI/Moryx.Resources.UI.csproj
  src/StartProject/StartProject.csproj
  src/Tests/Moryx.AbstractionLayer.UI.Tests/Moryx.AbstractionLayer.UI.Tests.csproj
  src/Tests/Moryx.Products.IntegrationTests/Moryx.Products.IntegrationTests.csproj
  src/Tests/Moryx.Resources.Management.Tests/Moryx.Resources.Management.Tests.csproj
Labels: enhancement

#44 Split of repository properties and common properties and package update
  .build/BuildToolkit.ps1
  .build/Common.props
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  src/Moryx.AbstractionLayer.TestTools/Moryx.AbstractionLayer.TestTools.csproj
  src/Moryx.AbstractionLayer.UI/Moryx.AbstractionLayer.UI.csproj
  src/Moryx.AbstractionLayer/Moryx.AbstractionLayer.csproj
  src/Moryx.Notifications/Moryx.Notifications.csproj
  src/Moryx.Products.Management/Modification/Wcf/IProductInteraction.cs
  src/Moryx.Products.Management/Moryx.Products.Management.csproj
  src/Moryx.Products.Model/Moryx.Products.Model.csproj
  src/Moryx.Products.UI.Interaction/Moryx.Products.UI.Interaction.csproj
  src/Moryx.Products.UI/Moryx.Products.UI.csproj
  src/Moryx.Products.UI/Moryx.Products.UI.nuspec
  src/Moryx.Products.UI/packages.config
  src/Moryx.Resources.Interaction/AccessHost/IResourceInteraction.cs
  src/Moryx.Resources.Interaction/Moryx.Resources.Interaction.csproj
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
  src/Moryx.Resources.Samples/IVisualInstructor.cs
  src/Moryx.Resources.UI.Interaction/Moryx.Resources.UI.Interaction.csproj
  src/Moryx.Resources.UI/Moryx.Resources.UI.csproj
  src/StartProject.UI/StartProject.UI.csproj
  src/StartProject.UI/packages.config
  src/StartProject/StartProject.csproj
  src/StartProject/packages.config
  src/Tests/Moryx.AbstractionLayer.Tests/Moryx.AbstractionLayer.Tests.csproj
  src/Tests/Moryx.AbstractionLayer.UI.Tests/Moryx.AbstractionLayer.UI.Tests.csproj
  src/Tests/Moryx.Notifications.Tests/Moryx.Notifications.Tests.csproj
  src/Tests/Moryx.Products.IntegrationTests/Moryx.Products.IntegrationTests.csproj
  src/Tests/Moryx.Resources.Management.Tests/Moryx.Resources.Management.Tests.csproj
Labels: enhancement

#46 Final release fixes
  Directory.Build.targets
  src/Moryx.AbstractionLayer/Products/IProductInstance.cs
  src/Moryx.AbstractionLayer/Products/IProductManagement.cs
  src/Moryx.AbstractionLayer/Products/ProductInstance.cs
  src/Moryx.Products.Management/Components/IProductInstanceStrategy.cs
  src/Moryx.Products.Management/Components/IProductManager.cs
  src/Moryx.Products.Management/Components/IProductStorage.cs
  src/Moryx.Products.Management/Facades/ProductManagementFacade.cs
  src/Moryx.Products.Management/Implementation/ProductManager.cs
  src/Moryx.Products.Management/Implementation/Storage/InstanceStrategyBase.cs
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Moryx.Products.Management/Modification/Model/WorkplanModel.cs
  src/Moryx.Products.Management/Plugins/GenericStrategies/GenericInstanceStrategy.cs
  src/Moryx.Products.Management/Plugins/NullStrategies/SkipArticlesStrategy.cs
  src/Moryx.Products.Samples/Strategies/WatchStrategy.cs
Labels: bug

#48 Fix null reference if client was not connected
  src/Moryx.Products.UI/ProductServiceModel.cs
  src/Moryx.Resources.UI/ResourceServiceModel.cs
Labels: area:ProductManagement, area:ResourceManagement, bug

#47 EntrySerialize for resources, products and recipes
  src/Moryx.Products.Management/Modification/PartialSerialization.cs
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Products.Management/Modification/Wcf/ProductInteraction.cs
  src/Moryx.Products.Samples/Recipe/WatchProductRecipe.cs
  src/Moryx.Resources.Management/Resources/ResourceSerialization.cs
Labels: area:ProductManagement, area:ResourceManagement, enhancement

#50 Exception handling in AL endpoints
  src/Moryx.Products.Management/Components/IProductManager.cs
  src/Moryx.Products.Management/Facades/ProductManagementFacade.cs
  src/Moryx.Products.Management/Implementation/ProductManager.cs
  src/Moryx.Products.Management/Modification/IProductConverter.cs
  src/Moryx.Products.Management/Modification/IProductConverterFactory.cs
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Products.Management/Modification/Wcf/IProductInteraction.cs
  src/Moryx.Products.Management/Modification/Wcf/ProductInteraction.cs
  src/Moryx.Resources.Interaction/AccessHost/ResourceInteraction.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: area:ProductManagement, area:ResourceManagement, enhancement
