Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2020-07, with the labels that each got.

#11 Removed abstract limitation from ProductImporterConfig
  src/Moryx.Products.Management/Components/ProductImporterConfig.cs
Labels: area:ProductManagement

#14 Removed default importer config because it is not necessary
  src/Moryx.AbstractionLayer/Products/Import/IPrototypeParameters.cs
  src/Moryx.Products.Management/Implementation/Import/ProductImporterBase.cs
  src/Moryx.Products.Management/Implementation/Import/PrototypeImportParameters.cs
  src/Moryx.Products.Management/ModuleController/ModuleConfig.cs
  src/Moryx.Products.Management/Moryx.Products.Management.csproj
  src/Moryx.Products.Management/Plugins/Importers/DefaultImporter.cs
  src/Moryx.Products.Management/Plugins/Importers/DefaultImporterConfig.cs
Labels: area:ProductManagement, enhancement

#15 Update outdated documentation and fix broken screenshots
  docs/articles/AbstractionLayer.md
  docs/articles/Products/ProductDefinition.md
  docs/articles/Products/ProductStorage.md
  docs/articles/Tutorials/HowToBuildADriver.md
  docs/articles/Tutorials/images/ExampleDriverResourceUI.png
Labels: documentation

#17 Update Capabilities.md
  docs/articles/Processing/Capabilities.md
Labels: documentation
