Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2021-01, with the labels that each got.

#65 Support cross platform resource manager without WCF support
  src/Moryx.Resources.Management/ModuleController/ModuleController.cs
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
  src/Moryx.Resources.Management/Resources/ReferenceCollection.cs
  src/Moryx.Resources.Management/Resources/ResourceGraph.cs
  src/Moryx.Resources.Management/Resources/ResourceProxyBuilder.cs
  src/Moryx.Resources.Management/Resources/ResourceReferenceTools.cs
Labels: area:ResourceManagement, enhancement

#63 Introduced activity parameters with instance populate
  VERSION
  src/Moryx.AbstractionLayer/Activities/Parameters.cs
  src/Moryx.AbstractionLayer/Activities/ParametersBase.cs
  src/Tests/Moryx.AbstractionLayer.Tests/ParameterBindingTests.cs
  src/Tests/Moryx.Products.IntegrationTests/RecipeStorage/TaskA.cs
  src/Tests/Moryx.Products.IntegrationTests/RecipeStorage/TaskB.cs
Labels: area:Abstraction, enhancement

#67 Fixed null equals comparison in HasChanged of ColumnMapper
  VERSION
  src/Moryx.Products.Management/Plugins/GenericStrategies/PropertyMapper.cs
  src/Moryx.Products.Samples/ProductTypes/WatchfaceType.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: bug

#68 Fix typos and make improvements in docs
  docs/articles/AbstractionLayer.md
  docs/articles/Processing/Activities.md
  docs/articles/Processing/Capabilities.md
  docs/articles/Processing/Constraints.md
  docs/articles/Processing/Workplans.md
  docs/articles/Products/Concept.md
  docs/articles/Products/ProductDefinition.md
  docs/articles/Products/ProductImport.md
  docs/articles/Products/ProductManagement.md
  docs/articles/Products/ProductManagementUI.md
  docs/articles/Resources/ResourceTypeTree.md
  docs/docfx.json
  docs/manual/ProductUI.md
  docs/manual/ResourceUI.md
Labels: documentation

#69 Fixed interface type compliance of TextColumnMapper
  VERSION
  src/Moryx.Products.Management/Implementation/Storage/AutoConfigurator.cs
  src/Moryx.Products.Management/Implementation/Storage/TextStrategyConfigurationAttribute.cs
  src/Tests/Moryx.Products.IntegrationTests/StrategyConfigurationAttributeTests.cs
Labels: bug
