Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2021-04, with the labels that each got.

#92 Removed obsoletes and todos for the next major
  VERSION
  src/Moryx.AbstractionLayer/Activities/IParameters.cs
  src/Moryx.AbstractionLayer/Activities/Parameters.cs
  src/Moryx.AbstractionLayer/Activities/ParametersBase.cs
  src/Moryx.AbstractionLayer/Capabilities/CapabilitiesBase.cs
  src/Moryx.AbstractionLayer/Capabilities/CombinedCapabilities.cs
  src/Moryx.AbstractionLayer/Capabilities/ConcreteCapabilities.cs
  src/Moryx.AbstractionLayer/Recipes/IRecipe.cs
  src/Moryx.AbstractionLayer/Recipes/IRecipeTemplating.cs
  src/Moryx.AbstractionLayer/Recipes/Recipe.cs
  src/Moryx.AbstractionLayer/Recipes/RecipeReference.cs
  src/Moryx.AbstractionLayer/Resources/Attributes/AvailableCapabilitiesAttribute.cs
  src/Moryx.Products.Management/Implementation/RecipeStorage.cs
  src/Moryx.Products.Model/Entities/ProductRecipeEntity.cs
Labels: area:Abstraction, enhancement

#94 Compare new notifications by reference and prevent Guid overwrite
  src/Moryx.Notifications/Adapter/NotificationAdapter.cs
Labels: bug

#95 Select ResourceAvailableAsAttribute from base classes
  src/Moryx.Resources.Management/Resources/ResourceTypeController.cs
Labels: area:ResourceManagement, bug

#100 Fix setting collections through resource proxies
  src/Moryx.Resources.Management/Resources/ResourceProxy.cs
  src/Moryx.Resources.Management/Resources/ResourceProxyBuilder.cs
  src/Moryx.Resources.Management/Resources/ResourceTypeController.cs
  src/Tests/Moryx.Resources.Management.Tests/Mocks/ReferenceResource.cs
  src/Tests/Moryx.Resources.Management.Tests/TypeControllerTests.cs
Labels: area:ResourceManagement, bug

#97 Added reference class for IProductRecipe
  VERSION
  src/Moryx.AbstractionLayer/Recipes/ProductRecipeReference.cs
  src/Moryx.AbstractionLayer/Recipes/RecipeReference.cs
Labels: area:Abstraction, area:ProductManagement

#98 Enabled text search in recipe workplan selection
  src/Moryx.Products.UI.Interaction/Recipes/Details/Default/DefaultRecipeDetailsView.xaml
Labels: area:ProductManagement, enhancement

#101 Fixed loading recipes by classification mask
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: bug

#102 Fixed wrong recipe classification for loading all recipes
  src/Moryx.Products.Management/Implementation/RecipeManagement.cs
Labels: bug
