Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2021-02, with the labels that each got.

#72 Do not save empty Guid in TextColumnMapper
  src/Moryx.Products.Management/Plugins/GenericStrategies/TextColumnMapper.cs
Labels: area:ProductManagement, bug

#75 Added missing ReplaceOrigin call to set the origin for new recipes
  src/Moryx.Products.Management/Facades/ProductManagementFacade.cs
Labels: bug

#73 Minor capabilities clean up
  docs/articles/Processing/Capabilities.md
  src/Moryx.AbstractionLayer/Capabilities/Capabilities.cs
  src/Moryx.AbstractionLayer/Capabilities/CombinedCapabilities.cs
  src/Moryx.AbstractionLayer/Capabilities/ConcreteCapabilities.cs
  src/Moryx.AbstractionLayer/Capabilities/NullCapabilities.cs
  src/Moryx.AbstractionLayer/Process/ProcessBindingResolverFactory.cs
  src/Moryx.AbstractionLayer/Resources/Attributes/AvailableCapabilitiesAttribute.cs
  src/Moryx.Resources.Management/Resources/ResourceTypeController.cs
Labels: area:Abstraction, enhancement

#66 Added missing WorkplanExtensions for activities with interface parameters
  src/Moryx.AbstractionLayer/Workplan/WorkplanExtensions.cs
Labels: enhancement

#80 Fixed product import saves partlinks redundant
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: area:ProductManagement, bug

#81 Fix NullReference in IdentifierResolver
  src/Moryx.AbstractionLayer/Process/ProcessBindingResolverFactory.cs
Labels: bug
