Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2022-01, with the labels that each got.

#140 Additional facade for bare access and modification of resources
  src/Moryx.AbstractionLayer/Products/ProductFacadeExtensions.cs
  src/Moryx.AbstractionLayer/Resources/IResourceGraph.cs
  src/Moryx.AbstractionLayer/Resources/IResourceModification.cs
  src/Moryx.AbstractionLayer/Resources/ResourceFacadeExtensions.cs
  src/Moryx.Resources.Management/Facades/ResourceManagementFacade.cs
Labels: enhancement, area:ResourceManagement, area:ProductManagement

#143 Update EntryViewModels instead of replacing them
  Directory.Build.targets
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/CollectionPartConnectorViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/SinglePartConnectorPartViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Import/ImportParameterViewModel.cs
  src/Moryx.Products.UI.Interaction/Products/Import/ImporterViewModel.cs
  src/Moryx.Products.UI/ViewModels/PartConnectorViewModel.cs
  src/Moryx.Products.UI/ViewModels/PartLinkViewModel.cs
  src/Moryx.Products.UI/ViewModels/ProductViewModel.cs
  src/Moryx.Products.UI/ViewModels/RecipeViewModel.cs
  src/Moryx.Resources.UI.Interaction/Details/Aspects/Methods/ResourceMethodsAspectViewModel.cs
  src/Moryx.Resources.UI/ConstructorViewModel.cs
  src/Moryx.Resources.UI/ResourceMethodViewModel.cs
  src/Moryx.Resources.UI/ResourceViewModel.cs
Labels: bug

#146 Filter instance by type expression
  src/Moryx.Products.Management/Implementation/Storage/ProductExpressionHelpers.cs
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Moryx.Resources.Interaction/Moryx.Resources.Interaction.csproj
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: enhancement, area:ProductManagement

#141 Add Unit tests for ProductConverter and Bug Fixes
  AbstractionLayer.sln
  src/Moryx.AbstractionLayer.TestTools/DummyProductPartLink.cs
  src/Moryx.AbstractionLayer.TestTools/DummyProductRecipe.cs
  src/Moryx.AbstractionLayer.TestTools/DummyProductType.cs
  src/Moryx.AbstractionLayer.TestTools/DummyWorkplan.cs
  src/Moryx.AbstractionLayer/Products/ProductType.cs
  src/Moryx.Products.Management/Modification/Model/ProductFileModel.cs
  src/Moryx.Products.Management/Modification/Model/ProductModel.cs
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Products.Management/Properties/AssemblyInfo.cs
  src/Moryx.Products.UI/Connected Services/ProductService/Reference.cs
  src/Moryx.Products.UI/IProductServiceModel.cs
  src/Tests/Moryx.Products.Management.Tests/Moryx.Products.Management.Tests.csproj
  src/Tests/Moryx.Products.Management.Tests/ProductConverterTests.cs
Labels: bug, enhancement, area:ProductManagement

#134 Lock the classification dropdown in the DefaultRecipeView for Cloned Recipes
  src/Moryx.Products.Management/Modification/Endpoint/IProductInteraction.cs
  src/Moryx.Products.Management/Modification/Model/RecipeModel.cs
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Products.UI.Interaction/Recipes/Details/Default/DefaultRecipeDetailsView.xaml
  src/Moryx.Products.UI.Interaction/Recipes/Details/Default/DefaultRecipeDetailsViewModel.cs
  src/Moryx.Products.UI/Connected Services/ProductService/Reference.cs
  src/Moryx.Products.UI/ProductServiceModel.cs
  src/Moryx.Products.UI/ViewModels/RecipeViewModel.cs
Labels: enhancement, area:ProductManagement

#142 Add Workplan Model to Recipe Model
  src/Moryx.Products.Management/Modification/Model/RecipeModel.cs
  src/Moryx.Products.Management/Modification/ProductConverter.cs
  src/Moryx.Products.UI.Interaction/Recipes/Details/RecipeDetailsViewModelBase.cs
  src/Moryx.Products.UI/Connected Services/ProductService/Reference.cs
Labels: bug, enhancement, area:ProductManagement

#149 Fix NullReference exception on PartLinks
  src/Moryx.Products.UI.Interaction/Products/Aspects/Parts/SinglePartConnectorPartViewModel.cs
Labels: bug, area:ProductManagement

#150 Hotfix: Load instance by type calls wrong overload
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Tests/Moryx.Products.IntegrationTests/ProductStorageTests.cs
Labels: bug, area:ProductManagement

#151 Set Service Version of Http Endpoint to 5.1.0
  src/Moryx.Products.Management/Modification/Endpoint/ProductInteraction.cs
Labels: bug, area:ProductManagement

#152 Replace Activity<T> with IActivity<T> in WorkplanExtension
  src/Moryx.AbstractionLayer/Workplan/WorkplanExtensions.cs
Labels: bug, area:Abstraction
