Repository PHOENIXCONTACT/MORYX-AbstractionLayer, pull requests merged in 2022-03, with the labels that each got.

#156 Provide typed initializer for resource creation
  src/Moryx.AbstractionLayer/Resources/ResourceFacadeExtensions.cs
Labels: enhancement, area:ResourceManagement

#154 Extend NotificationPublisher API
  src/Moryx.Notifications/INotificationPublisher.cs
  src/Moryx.Notifications/INotificationPublisherExtended.cs
  src/Moryx.Notifications/Notification/INotification.cs
  src/Moryx.Notifications/Notification/Notification.cs
Labels: enhancement, area:Abstraction

#158 Set identifier on object instatiation for Notifications
  src/Moryx.Notifications/Notification/Notification.cs
Labels: bug, area:Abstraction

#159 Extend ResourceManagemt Facade to provide the TypeTree
  src/Moryx.Resources.Management/Facades/ResourceManagementFacade.cs
Labels: enhancement, area:ResourceManagement
